### ISSUE TITLE
Хранение переменной res

### ISSUE THREAD

**Issue by sergeysablin99** [sergeysablin99/Millionare#4]
В данный момент переменная **res**, отвечающая за предоставления ответа навыку статична и находится в функции form_response. Однако, результат обработки запроса для диалога, диалога авторизации, меню и самой игры разные. Предлагаю получать значение **res** непосредственно из класса, который в данный момент обрабатывает пользователя.

**Comment by exeynod** [comment]
На данный момент да, но когда мы будем использовать кнопки, то класс будет иметь атрибут buttons и много других, которые придется обработать дополнительно

**Comment by sergeysablin99** [comment]
В любом случае, хранение будет вне функции form_response, да?

**Comment by exeynod** [comment]
Хранение в классе конечно. Посмотри на мои прошлые проекты. Там это достаточно хорошо реализовано
